import type { Payer } from '../../domain'
import { PAYMENT_METHODS } from '../../domain'
import { formatCurrency, parseCurrency } from '../../money'
import { Field, Switch, Badge } from './ui'

const isCard = (method: number) => method === 202410000
const emailValid = (email: string) => /^\S+@\S+\.\S+$/.test(email.trim())

export function PayerRow({ payer, onChange }: { payer: Payer; onChange: (change: Partial<Payer>) => void }) {
  const cardPayment = isCard(payer.paymentMethod)
  const linkFailed = payer.linkStatus === 'Failed'
  const emailError = cardPayment && payer.generateLink && !emailValid(payer.email)
  return <article className={`payer-row ${emailError ? 'has-error' : ''}`}><header className="payer-row__header"><div className="payer-identity"><strong>{payer.name}</strong><small>{payer.role} · {payer.email || 'Sem e-mail cadastrado'}</small></div><Badge tone={linkFailed ? 'danger' : payer.existingPayerId ? 'info' : 'success'}>{linkFailed ? 'Falha no link' : payer.paymentStatus ?? 'Novo pagante'}</Badge></header><div className="payer-row__controls"><Field label="Valor"><input inputMode="decimal" aria-label={`Valor de ${payer.name}`} value={formatCurrency(payer.amountCents)} onChange={(event) => { const cents = parseCurrency(event.target.value); if (cents !== null) onChange({ amountCents: cents }) }} /></Field><Field label="Forma de cobrança"><select value={payer.paymentMethod} onChange={(event) => { const method = Number(event.target.value) as Payer['paymentMethod']; onChange({ paymentMethod: method, generateLink: isCard(method) ? payer.generateLink : false, sendEmail: isCard(method) ? payer.sendEmail : false }) }}>{PAYMENT_METHODS.map((method) => <option key={method.value} value={method.value}>{method.label}</option>)}</select></Field></div>{cardPayment ? <section className="payer-delivery" aria-label={`Link de pagamento de ${payer.name}`}><div className="payer-delivery__heading"><div><span>Link de pagamento</span><small>Gere um link para esta cobrança.</small></div><Switch label="Gerar link" checked={payer.generateLink} onChange={(checked) => onChange({ generateLink: checked, sendEmail: checked ? payer.sendEmail : false })} /></div>{payer.generateLink ? <div className="payer-delivery__details"><Field label="E-mail do recebedor" hint={emailError ? 'Informe um e-mail válido para gerar o link.' : undefined}><input type="email" aria-label={`E-mail de ${payer.name}`} aria-invalid={emailError} className={emailError ? 'is-invalid' : ''} value={payer.email} onChange={(event) => onChange({ email: event.target.value })} placeholder="nome@empresa.com.br" /></Field><Switch label="Enviar por e-mail" checked={payer.sendEmail} onChange={(checked) => onChange({ sendEmail: checked })} /></div> : <p className="payer-delivery__hint">O link não será criado para este pagante.</p>}</section> : <section className="payer-delivery payer-delivery--muted" aria-label="Cobrança sem link"><div><span>Link de pagamento</span><small>Indisponível para esta forma de cobrança.</small></div></section>}{linkFailed ? <p className="payer-row__error" role="alert">{payer.linkError || 'Revise o histórico do Flow antes de gerar novamente.'}</p> : null}{payer.paymentUrl ? <a className="payer-link" href={payer.paymentUrl} target="_blank" rel="noreferrer">Abrir link gerado</a> : null}</article>
}
