import type { Payer } from '../../domain'
import { PAYMENT_METHODS } from '../../domain'
import { formatCurrency, parseCurrency } from '../../money'
import { Field, Switch, Badge } from './ui'

const isCard = (method: number) => method === 202410000
const emailValid = (email: string) => /^\S+@\S+\.\S+$/.test(email.trim())

export function PayerRow({ payer, onChange }: { payer: Payer; onChange: (change: Partial<Payer>) => void }) {
  const cardPayment = isCard(payer.paymentMethod)
  const linkFailed = payer.linkStatus === 'Failed'
  const emailError = payer.sendEmail && !emailValid(payer.email)
  const statusBadge = linkFailed ? <Badge tone="danger">Falha no link</Badge> : payer.paymentStatus ? <Badge tone="info">{payer.paymentStatus}</Badge> : null
  return <article className={`payer-review-row ${emailError ? 'payer-review-row--error' : ''}`}><div className="payer-review-row__person"><div><strong>{payer.name}</strong>{statusBadge}</div><small>{payer.role}</small></div><div className="payer-review-row__contact"><span>{payer.email || 'Sem e-mail cadastrado'}</span><small>{payer.phone || 'Sem telefone cadastrado'}</small></div><Field label="Forma de cobrança"><select value={payer.paymentMethod} onChange={(event) => { const method = Number(event.target.value) as Payer['paymentMethod']; onChange({ paymentMethod: method, generateLink: isCard(method) ? payer.generateLink : false, sendEmail: isCard(method) ? payer.sendEmail : false }) }}>{PAYMENT_METHODS.map((method) => <option key={method.value} value={method.value}>{method.label}</option>)}</select></Field><Field label="Valor"><input inputMode="decimal" aria-label={`Valor de ${payer.name}`} value={formatCurrency(payer.amountCents)} onChange={(event) => { const cents = parseCurrency(event.target.value); if (cents !== null) onChange({ amountCents: cents }) }} /></Field><div className="payer-review-row__link">{cardPayment ? <Switch label="Gerar link" checked={payer.generateLink} onChange={(checked) => onChange({ generateLink: checked, sendEmail: checked ? payer.sendEmail : false })} /> : <small>Sem link</small>}</div>{cardPayment && payer.generateLink ? <div className="payer-review-row__email"><Switch label="Enviar por e-mail" checked={payer.sendEmail} onChange={(checked) => onChange({ sendEmail: checked })} />{payer.sendEmail ? <Field label="E-mail do recebedor" hint={emailError ? 'Informe um e-mail válido para enviar o link.' : undefined}><input type="email" aria-label={`E-mail de ${payer.name}`} aria-invalid={emailError} className={emailError ? 'is-invalid' : ''} value={payer.email} onChange={(event) => onChange({ email: event.target.value })} placeholder="nome@empresa.com.br" /></Field> : <small>Link será gerado para compartilhamento manual.</small>}</div> : null}{linkFailed ? <p className="payer-review-row__error" role="alert">{payer.linkError || 'Revise o histórico do Flow antes de gerar novamente.'}</p> : null}{payer.paymentUrl ? <a className="payer-review-row__url" href={payer.paymentUrl} target="_blank" rel="noreferrer">Abrir link gerado</a> : null}</article>
}
