import { ArrowLeft, Check, Mail, Pencil, ReceiptText, Search } from 'lucide-react'
import { useMemo, useState } from 'react'
import type { Payer, Person } from '../../domain'
import { Button } from './ui'

const emailValid = (email: string) => /^\S+@\S+\.\S+$/.test(email.trim())

function recipientFor(payer: Payer, people: Person[]): Person {
  return people.find((person) => person.id === (payer.recipientId ?? payer.id)) ?? { id: payer.recipientId ?? payer.id, name: payer.recipientName ?? payer.name, email: payer.recipientEmail ?? payer.email, phone: payer.phone, role: payer.role }
}

export function RecipientConfirmation({ payers, people, onChange, onBack }: { payers: Payer[]; people: Person[]; onChange: (payerId: string, recipient: Person) => void; onBack: () => void }) {
  const [searchingFor, setSearchingFor] = useState<string | null>(null)
  const [query, setQuery] = useState('')
  const eligible = payers.filter((payer) => payer.generateLink && payer.sendEmail)
  const choices = useMemo(() => people.filter((person) => `${person.name} ${person.email} ${person.role}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))), [people, query])

  return <section className="panel recipient-confirmation"><div className="recipient-confirmation__header"><div><span className="section-kicker">3. DESTINATÁRIOS</span><h2>Confirme quem recebe</h2><p>Revise o e-mail de cada cobrança antes de gerar.</p></div><Button variant="ghost" className="button-compact recipient-confirmation__back" onClick={onBack}><ArrowLeft size={15} />Revisão</Button></div><div className="recipient-confirmation__list">{eligible.map((payer) => { const recipient = recipientFor(payer, people); const isSearching = searchingFor === payer.id; const validRecipient = emailValid(recipient.email); return <article className={`recipient-card ${validRecipient ? '' : 'recipient-card--error'}`} key={payer.id}><div className="recipient-card__receipt"><ReceiptText size={17} aria-hidden="true" /><span>Recibo em nome de <strong>{payer.name}</strong></span></div><div className="recipient-card__current"><div className="recipient-card__mail-icon" aria-hidden="true"><Mail size={18} /></div><div className="recipient-card__identity"><span>DESTINATÁRIO</span><strong>{recipient.name}</strong><small>{recipient.email || 'Sem e-mail cadastrado'}</small></div><Button variant="ghost" className="recipient-card__change" aria-label={`Alterar destinatário de ${payer.name}`} aria-expanded={isSearching} onClick={() => { setSearchingFor(isSearching ? null : payer.id); setQuery('') }}><Pencil size={15} />{isSearching ? 'Fechar' : 'Alterar'}</Button></div>{!validRecipient ? <p className="recipient-card__error" role="alert">Escolha uma pessoa com e-mail cadastrado.</p> : null}{isSearching ? <div className="recipient-search"><label className="search-field"><Search size={17} aria-hidden="true" /><span className="sr-only">Buscar destinatário para {payer.name}</span><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por nome ou e-mail" /></label><fieldset className="recipient-options"><legend className="sr-only">Escolha o destinatário de {payer.name}</legend>{choices.length ? choices.map((person) => { const selected = recipient.id === person.id; const valid = emailValid(person.email); return <label className={`recipient-option ${selected ? 'is-selected' : ''} ${valid ? '' : 'is-disabled'}`} key={person.id}><input type="radio" name={`recipient-${payer.id}`} checked={selected} disabled={!valid} onChange={() => { onChange(payer.id, person); setSearchingFor(null); setQuery('') }} /><span className="recipient-option__avatar" aria-hidden="true">{person.name.charAt(0)}</span><span className="recipient-option__identity"><strong>{person.name}</strong><small>{person.role} · {person.email || 'Sem e-mail cadastrado'}</small></span>{selected ? <Check size={17} aria-hidden="true" /> : null}</label>}) : <p className="recipient-search__empty">Nenhuma pessoa encontrada.</p>}</fieldset></div> : null}</article>})}</div></section>
}
